create database loan_platform;

create table loan_workflow(
id BIGINT(10) AUTO_INCREMENT PRIMARY KEY,
front_office VARCHAR(30),/*! PENDING,ACCEPTED,REJECTED,REVIEW */
carloan_office VARCHAR(30),/*! PENDING,ACCEPTED,REJECTED,REVIEW */
risk_office VARCHAR(30),/*! PENDING,ACCEPTED,REJECTED,REVIEW */
disbursal_office VARCHAR(30),/*! PENDING,ACCEPTED,REJECTED,REVIEW */
update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

